name: Unified Deploy (PR/dev/qa/stage/prod)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feat/**'
      - 'qa/**'
      - 'release/**'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number for preview (optional)'
        required: false

permissions:
  contents: write

concurrency:
  group: "deploy-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          (npm ci) || npm install
      - name: Build
        run: npm run build
      - name: Smoke test build artifacts
        run: |
          set -e
          test -f dist/index.html
          test -f dist/style.css
          test -f dist/app.js
          test -f dist/discovery.html
          test -f dist/discovery-table.html
          test -f dist/discovery-table.js
          grep -qi '<title' dist/index.html
          grep -qi 'class="app-container"' dist/index.html
          echo "Smoke tests passed"
      - name: Determine mode and destination
        id: mode
        env:
          PR_NUMBER_INPUT: ${{ github.event.inputs.pr_number }}
        run: |
          set -euo pipefail
          EVENT="${GITHUB_EVENT_NAME}"
          REF="${GITHUB_REF}"
          SHA="${GITHUB_SHA:0:7}"
          MODE=""; NAME=""; DEST="";
          if [ "$EVENT" = "pull_request" ]; then
            # Use PR number from context
            MODE=preview
            PRNUM=$(jq -r .pull_request.number < "$GITHUB_EVENT_PATH")
            NAME="pr-${PRNUM}"
            DEST="env/$MODE/$NAME"
          else
            case "$REF" in
              refs/heads/feat/*)  MODE=dev;   NAME=${REF#refs/heads/} ;;
              refs/heads/qa/*)    MODE=qa;    NAME=${REF#refs/heads/} ;;
              refs/heads/release/*) MODE=stage; NAME=${REF#refs/heads/} ;;
              refs/heads/main)    MODE=qa;    NAME=main-${SHA} ;;
              refs/tags/v*-rc*)   MODE=stage; NAME=${REF#refs/tags/} ;;
              refs/tags/v*)       MODE=prod;  NAME=${REF#refs/tags/} ;;
              *) MODE="" ;;
            esac
            if [ -n "$MODE" ]; then DEST="env/$MODE/$NAME"; fi
          fi
          if [ -z "$MODE" ] || [ -z "$DEST" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "No matching mode for event=$EVENT ref=$REF; skipping publish"
            exit 0
          fi
          echo "mode=$MODE" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "dest=$DEST" >> $GITHUB_OUTPUT
          echo "url=https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/$DEST/" >> $GITHUB_OUTPUT
      - name: Publish to gh-pages (accumulate envs)
        if: steps.mode.outputs.skip != 'true'
        env:
          MODE: ${{ steps.mode.outputs.mode }}
          NAME: ${{ steps.mode.outputs.name }}
          DEST: ${{ steps.mode.outputs.dest }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          mkdir -p repo
          cd repo
          git init
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch origin gh-pages:gh-pages || true
          if git rev-parse --verify gh-pages >/dev/null 2>&1; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            rm -rf ./* .[^.]* || true
            printf '%s' '<!DOCTYPE html><title>Build Catalog</title><h1>Build Catalog</h1>' > index.html
            git add index.html
            git commit -m "chore: init gh-pages"
          fi
          mkdir -p "$(dirname "$DEST")"
          rm -rf "$DEST"
          mkdir -p "$DEST"
          cp -R ../dist/* "$DEST"/
          if [ "$MODE" != "preview" ]; then
            rm -rf "env/$MODE/latest"
            mkdir -p "env/$MODE"
            cp -R "$DEST" "env/$MODE/latest"
          fi
          node -e '
            const fs=require("fs"),path=require("path");
            const env=process.env.MODE, dest=process.env.DEST; const name=process.env.NAME;
            const entry={ env, name, path: dest, commit: process.env.GITHUB_SHA, created_at: new Date().toISOString(), source: process.env.GITHUB_REF, type: env==="preview"?"preview":"build" };
            const root="env"; if(!fs.existsSync(root)) fs.mkdirSync(root);
            const mf=path.join(root,"manifest.json");
            let data={ envs:{ dev:[], qa:[], stage:[], prod:[], preview:[] }, updated_at: new Date().toISOString() };
            if(fs.existsSync(mf)) { try { data=JSON.parse(fs.readFileSync(mf,"utf8")); } catch(e){} }
            if(!data.envs) data.envs={}; if(!data.envs[env]) data.envs[env]=[];
            data.envs[env]=data.envs[env].filter(e=>e.path!==dest);
            data.envs[env].unshift(entry);
            data.envs[env]=data.envs[env].slice(0,100);
            data.updated_at=new Date().toISOString();
            fs.writeFileSync(mf, JSON.stringify(data,null,2));
            const doctype = '<' + '!DOCTYPE html>';
            const html=[doctype,'<meta charset="utf-8">','<title>Build Catalog</title>','<h1>Build Catalog</h1>',...Object.entries(data.envs).map(([k,arr])=>`<h2>${k}</h2><ul>`+arr.map(i=>`<li><a href="/${i.path}/">${i.name}</a> <small>${i.created_at} (${i.commit?.slice(0,7)||''})</small></li>`).join('')+"</ul>")].join('\n');
            fs.writeFileSync(path.join('.', 'index.html'), html);
          '
          git add "$DEST" env/manifest.json index.html
          if [ "$MODE" != "preview" ]; then git add "env/$MODE/latest"; fi
          git commit -m "deploy($MODE): $DEST (ref $GITHUB_REF @ ${GITHUB_SHA::7})" || true
          git push origin gh-pages
          cd -
      - name: Comment preview URL (PRs only)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request.number;
            const url = `https://${context.repo.owner}.github.io/${context.repo.repo}/env/preview/pr-${pr}/`;
            const body = `🚀 Preview deployed: ${url}`;
            github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: pr, body });
