name: Preview Deploy (PR)

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: "pages-preview-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-publish-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          (npm ci) || npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Publish PR preview to gh-pages (git push)
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin gh-pages:gh-pages || true
          if ! git rev-parse --verify gh-pages >/dev/null 2>&1; then
            git checkout --orphan gh-pages
            rm -rf ./* .[^.]* || true
            echo '<!doctype html><title>Build Catalog</title><p>gh-pages initialized' > index.html
            git add index.html
            git commit -m "chore: init gh-pages"
          else
            git checkout gh-pages
          fi
          DEST="env/preview/pr-${PR_NUMBER}"
          mkdir -p "$DEST"
          rm -rf "$DEST"/* || true
          cp -R dist/* "$DEST"/
          git add "$DEST"
          git commit -m "preview: ${DEST} from ${GITHUB_REF}@${GITHUB_SHA::7}" || true
          git push origin gh-pages
      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request.number;
            const url = `https://${context.repo.owner}.github.io/${context.repo.repo}/env/preview/pr-${pr}/`;
            const body = `🚀 Preview deployed: ${url}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body
            });
